### ISSUE TITLE
Spawners turn to pig when placed

### ISSUE THREAD

**Issue by idkallie** [ame94/GuiShopRecoded#1]
When someone buys a spawner it turns to pig. I have silk spawners installed.

**Comment by idkallie** [comment]
Also, when someone doesn't have enough money it's "emough" instead of enough

**Comment by ame94** [comment]
Sorry I missed this issue report, but as you might have guessed I have currently abandoned this project. With the way 1.13 now changes everything, it is unlikely I'll ever resume any work on it again.

Best regards
