### ISSUE TITLE
Error in the PLugin

### ISSUE THREAD

**Issue by Killer50019Gamer** [ame94/GuiShopRecoded#2]
I have the plugin installed.

i cant change it we''re all annyed as bedrock and cant load the id byw anything else !!

**Comment by ame94** [comment]
Can you explain your problem more clearly?
Which version of spigot (or whatever else) are you using?

**Comment by Killer50019Gamer** [comment]
Here is information:

1. Link https://picload.org/view/dcgdggla/1.png.html

2. Link https://picload.org/view/dcgdggll/2.png.html

3. Link https://picload.org/view/dcgdggli/3.png.html

I can not do anything it's always the bedrock

**Comment by ame94** [comment]
You're using Spigot 13.x which is almost completely incompatible with any plugin built for use with game versions 1.8 - 1.12.2. Older plugins work with block IDs, and from 1.13 on it doesn't work that way anymore, which is probably why you're only seeing bedrock.

Major changes are needed for this plugin to work with how things are done now, and I have no interest in doing that any time soon, if ever. By all means feel free to fork this project and make the changes yourself ;)

Read this post for more details: https://www.spigotmc.org/threads/bukkit-craftbukkit-spigot-bungeecord-1-13-development-builds.328883/
